server:
  port: 8105
spring:
  application:
    name: taxi-notification
  rabbitmq:
    host: 120.55.42.113
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: '{cipher}e672e2f0385f8a9261df6a803fccbabc8d6251c8ea7579eee344472456777967'
    template:
      retry:
        enabled: true
        max-attempts: 2
    listener:
      simple:
        acknowledge-mode: auto
  redis:
      host: 120.55.42.113
      port: 6370
      password: '{cipher}24462190beaad45fc90fd249abfc16af0cc2c49530702a35036314f6d08de5ef'
      timeout: 1800000
  data:
    mongodb:
      host: 120.55.42.113
      port: 27334
      database: notification
      authenticationDatabase: notification
      username: notification
      password: '{cipher}c9712f9e3620901030e4c5d353211085d501f6a6c6a8f6ca9b49ca91346bdcbe'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1cj68xrmcrqk78c.mysql.rds.aliyuncs.com:3306/taxi-notification?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: yoogurt
    password: '{cipher}2c7f1c5a93ef567cf5c643765fc19b1de03fce98b4006d8c77947bb5dd9db93b'
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.exmail.qq.com
    username: ServerManager@yoogonet.com
    password: '{cipher}13f1244e2ff748553d3bade10e4ecc920df880128c33db3be163e67fffacfa19'
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
            required: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20  # 发呆时间，即服务续约到期时间（缺省为90s）