spring:
  redis:
    host: 127.0.0.1
    database: 15
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 100ms
  data:
    mongodb:
      database: timer
      host: localhost
      port: 27017
      repositories:
        type: auto
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    connection-timeout: 7000
    virtual-host: /
    username: root
    password: root
    listener:
      simple:
        acknowledge-mode: auto
  datasource:
    url: jdbc:mysql://localhost:3306/taxi-arrangement?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password:
    # 使用Hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver